version: '2'
services:
    notifier-mongodb:
        image: mongo:latest
        container_name: "notifier-mongodb"
        environment:
          - MONGO_DATA_DIR=/data/db
        volumes:
          - mongodata:/data/db
        ports:
          - 27017:27017
        command: mongod
    notifier:
      build: .
      container_name: "3beca-notifier"
      environment:
        - NODE_ENV=production
        - MONGODB_URL=mongodb://notifier-mongodb
        - DATABASE_NAME=tribeca_notifier
      ports:
        - "30701:30701"
        - "9229:9229"
      depends_on:
        - notifier-mongodb
volumes:
  mongodata: