version: '2'
services:
    notifier-mongodb:
      image: mongo:4.2.0
      environment:
        - MONGO_DATA_DIR=/data/db
      volumes:
        - notifier-mongodb-storage:/data/db
      ports:
        - 27017:27017
    notifier:
      build: .
      environment:
        - NODE_ENV=production
        - MONGODB_URL=mongodb://notifier-mongodb
        - DATABASE_NAME=tribeca_notifier
      ports:
        - "30701:30701"
      depends_on:
        - notifier-mongodb
volumes:
  notifier-mongodb-storage: