{{- if gt (.Values.deployment.replicaCount | int) 1 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: tribeca-notifier-poddisruptionbudget
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: tribeca-notifier
  minAvailable: 1
{{- end }}
