FROM ubuntu:16.04

ARG PRIVATE_SSH_KEY

RUN apt-get update && apt-get install -y ssh
RUN mkdir -p "/root/.ssh"
RUN echo $PRIVATE_SSH_KEY >> /root/.ssh/id_rsa
RUN chmod 600 /root/.ssh/id_rsa
RUN ssh-keyscan tribeca.ovh >> /root/.ssh/known_hosts