apiVersion: apps/v1
kind: Deployment
metadata:
  name: tribeca-notifier
  labels:
    app: tribeca-notifier
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tribeca-notifier
  template:
    metadata:
      labels:
        run: tribeca-notifier
    spec:
      containers:
      - name: tribeca-notifier
        image: francescorivola/tribeca-notifier:latest
        ports:
        - containerPort: 30701
        readinessProbe:
          httpGet:
            path: /admin/check-health
            port: 30701
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /admin/check-health
            port: 30701
          initialDelaySeconds: 12
          periodSeconds: 5
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URL
          value: mongodb://10.1.1.1:27017
---
apiVersion: v1
kind: Service
metadata:
  name: tribeca-notifier
  labels:
    name: tribeca-notifier
spec:
  type: NodePort
  ports:
    - port: 30701
      targetPort: 30701
      nodePort: 30701
      name: tcp
  selector:
    run: tribeca-notifier