apiVersion: v1
kind: Service
metadata:
  name: tribeca-notifier
  labels:
    name: tribeca-notifier
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30701
      name: tcp
  selector:
    run: tribeca-notifier